# Generated by Django 2.2.10 on 2020-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200531_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmation',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
