# Generated by Django 2.2.13 on 2020-06-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
